del sparseBig.txt
del sparseBigTimeMultiThread.txt
del sparseBigTimeSingleThread.txt
del sparseBigTimeThreadPool.txt
del sparseBigTimeFast.txt
del sparseMed.txt
del sparseMedTimeMultiThread.txt
del sparseMedTimeSingleThread.txt
del sparseMedTimeThreadPool.txt
del sparseMedTimeFast.txt
del sparseSmall.txt
del sparseSmallTimeMultiThread.txt
del sparseSmallTimeSingleThread.txt
del sparseSmallTimeThreadPool.txt
del sparseSmallTimeFast.txt

del midDenseBig.txt
del midDenseBigTimeMultiThread.txt
del midDenseBigTimeSingleThread.txt
del midDenseBigTimeThreadPool.txt
del midDenseBigTimeFast.txt
del midDenseMed.txt
del midDenseMedTimeMultiThread.txt
del midDenseMedTimeSingleThread.txt
del midDenseMedTimeThreadPool.txt
del midDenseMedTimeFast.txt
del midDenseSmall.txt
del midDenseSmallTimeMultiThread.txt
del midDenseSmallTimeSingleThread.txt
del midDenseSmallTimeThreadPool.txt
del midDenseSmallTimeFast.txt

del 10VBig.txt
del 10VBigTimeMultiThread.txt
del 10VBigTimeSingleThread.txt
del 10VBigTimeThreadPool.txt
del 10VBigTimeFast.txt
del 10VMed.txt
del 10VMedTimeMultiThread.txt
del 10VMedTimeSingleThread.txt
del 10VMedTimeThreadPool.txt
del 10VMedTimeFast.txt
del 10VSmall.txt
del 10VSmallTimeMultiThread.txt
del 10VSmallTimeSingleThread.txt
del 10VSmallTimeThreadPool.txt
del 10VSmallTimeFast.txt

del denseBig.txt
del denseBigTimeMultiThread.txt
del denseBigTimeSingleThread.txt
del denseBigTimeThreadPool.txt
del denseBigTimeFast.txt
del denseMed.txt
del denseMedTimeMultiThread.txt
del denseMedTimeSingleThread.txt
del denseMedTimeThreadPool.txt
del denseMedTimeFast.txt
del denseSmall.txt
del denseSmallTimeMultiThread.txt
del denseSmallTimeSingleThread.txt
del denseSmallTimeThreadPool.txt
del denseSmallTimeFast.txt